server:
  port: 8761

spring:
  application:
    name: eureka-server
  cloud:
    config:
      uri: http://localhost:8732
#      label: master
#      profile: dev
#      discovery:
#        service-id: config-server
#        enabled: true

eureka:
  instance:
    hostname: peer1
  client:
    #通过eureka.client.registerWithEureka：false和fetchRegistry：false来表明自己是一个eureka server.
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
        defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
